feat: GTP-00100 modified the code again

diff --git a/.github/workflows/demo1.yaml b/.github/workflows/demo1.yaml
--- a/.github/workflows/demo1.yaml
+++ b/.github/workflows/demo1.yaml
@@ -92,6 +92,26 @@ jobs:
           echo "Here we will swiitch to user user"
           sudo whoami
 
+      - name: Check docker is installed or not if not installed then install
+        id: check-docker
+        shell: bash
+        run: |
+          echo "we are checking docker ... "
+          if command -v docker &> /dev/null; then
+            echo $?
+            echo "Docker is already installed on runner"
+            docker --version
+          else:
+            echo "Docker is not found, Installing docker..."
+            curl -fsSL https://get.docker.com -o get-docker.sh
+            sudo sh get-docker.sh
+            sudo usermod -aG docker $USER
+            echo "Docker is installed successfully"
+            docker --version
+          fi
+
+          
+
 
 
 
